services:

  mysql:
    image: mysql:8
    container_name: mysql-shortener
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - ~/mysql-data:/var/lib/mysql
    networks:
      - url-shortener

  redis:
    image: redis:7
    container_name: redis-shortener
    ports:
      - "6379:6379"
    volumes:
      - ~/redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - url-shortener

  shortener-service:
    image: dev-env
    container_name: dev-shortener
    ports:
      - "8888:8888"
    volumes:
      - ~/workspace:/workspace
    networks:
      - url-shortener
    command: go run shortener.go
    depends_on:
      - mysql
      - redis

networks:
  url-shortener:
    driver: bridge