[SERVICE]
    Parsers_File /fluent-bit/etc/parsers.conf
    Log_Level info

[INPUT]
    Name tail
    Path /var/log/nginx/access.log
    Parser nginx_shortener
    Tag nginx.access
    Refresh_Interval 5
    Read_from_Head true

[OUTPUT]
    Name es
    Match nginx.access
    Host elasticsearch
    Port 9200
    Index nginx-access
    Logstash_Format On
    Logstash_Prefix nginx
    Replace_Dots On
