[PARSER]
    Name   nginx_shortener
    Format regex
    Regex  ^(?<remote_addr>[^ ]*) - (?<remote_user>[^ ]*) \[(?<time_local>[^\]]+)\] "(?<request>[^"]*)" (?<status>\d{3}) (?<body_bytes_sent>\d+) "(?<http_referer>[^"]*)" "(?<http_user_agent>[^"]*)" rt=(?<request_time>[^ ]*) ua="(?<upstream_addr>[^"]*)" us=(?<upstream_status>[^ ]*) urt=(?<upstream_response_time>[^ ]*) rid=(?<request_id>[^ ]*)$
    Time_Key time_local
    Time_Format %d/%b/%Y:%H:%M:%S %z
